### ISSUE TITLE
Some missing traits

### ISSUE THREAD

**Issue by IhateTrains** [cybrxkhan/VIET-Events-Reborn#12]
I've found some traits that are referenced in the events but are missing, maybe they should be readded?

- perceptive
- absentminded
- melodious_voice
- tall
- powerful_voice
- imposing
- agile

**Comment by cybrxkhan** [comment]
The congenital traits are still in my own personal mod, but I decided not to add them to this mod or reboot VIET Traits since I felt there was no need since there's several trait mods out there last I remember. Now that you bring it up, I've realized there's no point keeping the references to them even for my own personal mod since they're only used a few times so I think I'll just comment them out and/or change the references to other vanilla traits in the next update.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
